export type {
  AboutContent,
  AboutHighlight,
  AboutIconKey,
  ContactContent,
  ContactIconKey,
  ContactInfoItem,
  ExperienceContent,
  ExperienceItem,
  HeroContent,
  HireMeContent,
  HireMeIconKey,
  HireMeValue,
  ProjectItem,
  ProjectsContent,
  SectionHeader,
  SocialLink,
  TechIconKey,
  TechnologyItem,
} from "@/lib/content/schemas";
